#!/usr/bin/env node
'use strict';

/**
 * Bundle src/ + js-yaml into a single self-contained dist/action.js.
 *
 * GitHub Actions runs `runs.main` directly on the checked-out action — there is no
 * install step — so every dependency has to be inside that one file. Rather than
 * pull in a bundler (this package ships with exactly one runtime dependency), we
 * inline js-yaml's own UMD build plus our CommonJS modules behind a ~20 line
 * module registry. Node built-ins fall through to the real `require`.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(DIST, 'action.js');

const ENTRY = './action-main.js';

const SRC_MODULES = [
  'walk.js',
  'dockerfile-parse.js',
  'npm-config.js',
  'pnpm-commands.js',
  'findings.js',
  'check-dockerfiles.js',
  'check-workflows.js',
  'check-package-json.js',
  'report.js',
  'fix.js',
  'index.js',
  'action-main.js',
];

function readJsYamlUmd() {
  const candidates = [
    path.join(ROOT, 'node_modules', 'js-yaml', 'dist', 'js-yaml.js'),
    path.join(ROOT, 'node_modules', 'js-yaml', 'dist', 'js-yaml.min.js'),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return { source: fs.readFileSync(candidate, 'utf8'), from: candidate };
  }
  throw new Error(
    'js-yaml UMD build not found. Run `npm install` first (looked for node_modules/js-yaml/dist/js-yaml.js).'
  );
}

function wrap(id, source) {
  return [
    `__define(${JSON.stringify(id)}, function (module, exports, require) {`,
    source,
    '});',
    '',
  ].join('\n');
}

function build() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const jsYaml = readJsYamlUmd();

  const parts = [];
  parts.push('/*');
  parts.push(` * ${pkg.name} v${pkg.version} — GitHub Action bundle (generated by scripts/build-action.js)`);
  parts.push(' * DO NOT EDIT BY HAND. Run `npm run build`.');
  parts.push(' *');
  parts.push(` * ${pkg.name}: ${pkg.license} © ${pkg.author}`);
  parts.push(' * Bundled dependency: js-yaml (MIT) — https://github.com/nodeca/js-yaml');
  parts.push(' */');
  parts.push("'use strict';");
  parts.push('');
  parts.push('var __defs = Object.create(null);');
  parts.push('var __cache = Object.create(null);');
  parts.push('function __define(id, fn) { __defs[id] = fn; }');
  parts.push('function __resolve(id) {');
  parts.push('  if (__defs[id]) return id;');
  parts.push("  var stripped = id.replace(/^\\.\\//, '');");
  parts.push('  if (__defs[stripped]) return stripped;');
  parts.push("  if (__defs[stripped + '.js']) return stripped + '.js';");
  parts.push('  return null;');
  parts.push('}');
  parts.push('function __require(id) {');
  parts.push('  var key = __resolve(id);');
  parts.push('  if (key === null) return require(id);');
  parts.push('  if (__cache[key]) return __cache[key].exports;');
  parts.push('  var module = { exports: {} };');
  parts.push('  __cache[key] = module;');
  parts.push('  __defs[key].call(module.exports, module, module.exports, __require);');
  parts.push('  return module.exports;');
  parts.push('}');
  parts.push('');

  // package.json is required by src/index.js for the version string.
  parts.push(
    wrap(
      '../package.json',
      `module.exports = ${JSON.stringify({ name: pkg.name, version: pkg.version }, null, 2)};`
    )
  );

  parts.push(wrap('js-yaml', jsYaml.source));

  for (const name of SRC_MODULES) {
    const abs = path.join(SRC, name);
    if (!fs.existsSync(abs)) throw new Error(`Missing source module: ${abs}`);
    parts.push(wrap(name, fs.readFileSync(abs, 'utf8')));
  }

  parts.push(`__require(${JSON.stringify(ENTRY)});`);
  parts.push('');

  const bundle = parts.join('\n');

  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(OUT, bundle, 'utf8');

  const kb = (Buffer.byteLength(bundle, 'utf8') / 1024).toFixed(1);
  process.stdout.write(`built ${path.relative(ROOT, OUT)} (${kb} kB)\n`);
  process.stdout.write(`  bundled js-yaml from ${path.relative(ROOT, jsYaml.from)}\n`);
  process.stdout.write(`  modules: ${SRC_MODULES.length + 2}\n`);
}

try {
  build();
} catch (err) {
  process.stderr.write(`build-action: ${(err && err.message) || err}\n`);
  process.exitCode = 1;
}
